#!/usr/bin/env bash

# Linux Dotfiles Bootstrap

ln -s ~/Dropbox/dotfiles ~/.dotfiles

ln -s ~/.dotfiles/shell/.zshrc ~/.zshrc

ln -s ~/.dotfiles/git/.gitconfig ~/.gitconfig

ln -s ~/.dotfiles/vim/.vimrc ~/.vimrc
ln -s ~/.dotfiles/vim/.vimperatorrc ~/.vimperatorrc
ln -s ~/.dotfiles/vim/vimperator/colors ~/.vimperator/colors

ln -s ~/Dropbox/Tools/Keys/.ssh ~/.ssh

ln -s ~/.dotfiles/vscode/settings.json ~/.config/Code/User/settings.json
