#!/usr/bin/env bash

# Bootstrap a new configuration

# This doesn't work because you're in admin folder
#cd "$(dirname "$0")/.."

# So start in user's Dropbox/dotfiles/shell
cd ../../../
pwd

DOTFILES_ROOT=$(pwd)

set -e

echo ''

info () {
    printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
    printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
    echo ''
    exit
}

# Started using /J directory junctions instead of /D directory links. /J works better with apps and git,
# but found out that this causes problems with recursion in Dropbox. Switching back to /D

cmd <<< "mklink /D .ssh .tmp\Dropbox\Tools\Keys\.ssh"
cmd <<< "mklink /D .dotfiles .tmp\Dropbox\dotfiles"

cmd <<< "mklink .bashrc .dotfiles\shell\.bashrc"
cmd <<< "mklink .bash_profile .dotfiles\shell\.bash_profile"

cmd <<< "mklink .minttyrc .dotfiles\shell\.minttyrc"

cmd <<< "mklink .gitconfig .dotfiles\git\.gitconfig"

cmd <<< "mklink .vimrc .dotfiles\vim\.vimrc"
cmd <<< "mklink /D .vim\snippets ..\.dotfiles\vim\vim\snippets"

cmd <<< "mklink .vimperatorrc .dotfiles\vim\.vimperatorrc"
cmd <<< "mklink /D vimperator\colors ..\.dotfiles\vim\vimperator\colors"

# Deprecated
#cmd <<< "mklink .cvimrc .dotfiles\vim\.cvimrc"
#cmd <<< "mklink /D .vimfx .dotfiles\vimfx"
#cmd <<< "mklink /D .pentadactyl .dotfiles\pentadactyl\.pentadactyl"
#cmd <<< "mklink .pentadactylrc .dotfiles\pentadactyl\.pentadactylrc"
