#!/bin/bash

# Linux Dotfiles Bootstrap

ln -s ~/Dropbox/dotfiles ~/.dotfiles

ln -s ~/Dropbox/Tools/Vim/.vim ~/.vim

ln -s ~/.dotfiles/vim/.vimrc ~/.vimrc
ln -s ~/.dotfiles/vim/.vimperatorrc ~/.vimperatorrc
