#!/usr/bin/env bash

# Bootstrap a new configuration

# This doesn't work because you're in admin folder
#cd "$(dirname "$0")/.."

# So start in user's Dropbox/dotfiles/scripts
cd ../../../
pwd

DOTFILES_ROOT=$(pwd)

set -e

echo ''

info () {
    printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
    printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
    echo ''
    exit
}


cmd <<< "mklink /D .dotfiles Dropbox\dotfiles"

cmd <<< "mklink .bashrc .dotfiles\bash\.bashrc"
cmd <<< "mklink .bash_profile .dotfiles\bash\.bash_profile"

cmd <<< "mklink .minttyrc .dotfiles\bash\.minttyrc"

cmd <<< "mklink .gitconfig .dotfiles\git\.gitconfig"

cmd <<< "mklink /D .vim Dropbox\Tools\Vim\.vim"
cmd <<< "mklink .vimrc .dotfiles\vim\.vimrc"
cmd <<< "mklink .cvimrc .dotfiles\vim\.cvimrc"
cmd <<< "mklink .vimperatorrc .dotfiles\vim\.vimperatorrc"

cmd <<< "mklink /D .ssh Dropbox\Tools\Keys\.ssh"

# Deprecated
#cmd <<< "mklink /D .vimfx .dotfiles\vimfx"

#cmd <<< "mklink /D .pentadactyl .dotfiles\pentadactyl\.pentadactyl"
#cmd <<< "mklink .pentadactylrc .dotfiles\pentadactyl\.pentadactylrc"
